name: RELEASE

on:
  push:
    branches:
      - main

env:
  IMAGE_TAG: "lishuaidev/${{ github.event.repository.name }}:${{ github.sha }}"
  ATTESTATION_SUBJECT_NAME: "index.docker.io/lishuaidev/${{ github.event.repository.name }}"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Style Check And Test
        run: ./gradlew check --info

      - name: Build Jar
        run: ./gradlew clean bootJar --no-daemon --parallel

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_TAG }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.ATTESTATION_SUBJECT_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
